name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: 
     - develop
     - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
  
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: |
          ./gradlew assembleDebug
