name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: 
     - develop
     - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Android
    uses: ./.github/workflows/_build.yml
    secrets: inherit
