name: Release

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths-ignore:
      - '*.md'
      - .github/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Android
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  release:
    name: Release
    needs: [build]
    uses: ./.github/workflows/_git-release.yml
    secrets: inherit