name: Release

on:
  repository_dispatch:
    types: [new-sdk-version]
  workflow_dispatch:
    inputs:
      sdkVersion:
        description: 'SDK Version'
        required: true
        type: string
  # push:
  #   branches:
  #    - master
  #   paths-ignore:
  #     - '*.md'
  #     - .github/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  packages: read   # Lets default GITHUB_TOKEN access GitHub Packages (no PAT secret needed)

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Build Action
        uses: ./.github/actions/build-android
        with:
          gradle: assembleProd
          apkPath: app/build/outputs/apk/prod
          apkName: LeapDemo
          signing_key: ${{ secrets.SIGNING_KEY }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }} 
          key_alias: ${{ secrets.KEY_ALIAS }}